### ISSUE TITLE
New RoleSet Wizzard is broken

### ISSUE THREAD

**Issue by StephanOpfer** [carpe-noctem-cassel/alica-plan-designer#5]
If you try to create a new RolesSet.rset file, by using the context menu in the package explorer, you will get an empty wizzard window.

**Comment by Eome** [comment]
Fixed!

**Comment by StephanOpfer** [comment]
Deployed version is the same as the old version?

**Comment by Eome** [comment]
Sorry, forget to upload the files. Is definitely fixed now!
